FROM node:12.12.0-alpine

RUN apk add --no-cache git python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm install -g knex
RUN npm install
COPY . .

ENV NODE_ENV=test
ENV KEY=test_secret_key

CMD ["npm", "test"]